### ISSUE TITLE
Can I deploy the website myself?

### ISSUE THREAD

**Issue by jx2518** [jamespfennell/react-sandbox#40]
Hi, I am exploring your project and trying to add some new features in. So I forked the repo and tried to deploy the forked repo onto a new url but it didn't work. I deployed on Netlify. Although Netlify says deployed sucessfully and the index page is indeed rendered, when I clicked into any route buttom it just says "backend error". Could you please help, thank you!
<img width="265" alt="image" src="https://github.com/jamespfennell/realtimerail.nyc-react/assets/121977360/b1a4fa7f-b4e8-4bea-abd8-469e32393b3d">

**Comment by jamespfennell** [comment]
Thank you for filing the issue. I understand it's frustrating that I didn't respond quickly, but I do think that posting on other repos I'm working on to raise attention here is a bit...aggressive. You could have pinged me here again, or sent me an email.

---

Regarding the issue here, just some background info on how the app reaches the backend. The app contains [a baseUrl](https://github.com/jamespfennell/realtimerail.nyc-react/blob/9c797729a4a8172b1298707714f365aec258903c/src/api/api.ts#L3) at which the API is available. In this repo, this is set to `/transiter/v0.6/`. Thus in production, the app assumes there is a Transiter instance running on the same host, available at `$HOST_URL/transiter/v0.6/`. Do you have Transiter running and listening on that directory?

When running the app in dev mode locally (using `npm start`), the situation is a little different. There is a [proxy URL](https://github.com/jamespfennell/realtimerail.nyc-react/blob/9c797729a4a8172b1298707714f365aec258903c/package.json#L37) configured, currently set to `https://staging.realtimerail.nyc`. In this case all requests are routed to `https://staging.realtimerail.nyc/transiter/v0.6`.

**Comment by jx2518** [comment]
Hi, thank you very much for the explanation! I am really sorry to bother you especially in another repo as I didn't know how to pin people in the comment! I have deleted my comment there and would like to apologize again for my inpatience.

**Comment by jamespfennell** [comment]
It's all good :)

It would be great if we were able to figure out the issue you had! We could then update the README. The README is very sparse right now!

**Comment by jamespfennell** [comment]
Feel free to reopen if you have more questions! :)
