### ISSUE TITLE
MTA real time doesn't work

### ISSUE THREAD

**Issue by avrumi612** [jamespfennell/react-sandbox#46]
When going into the real-time app, it's coming up the below error
![Screenshot 2024-01-23 153846](https://github.com/jamespfennell/realtimerail.nyc/assets/157535169/436b6168-9b6b-4d64-a947-96e47fad1969)

**Comment by wellerbarry** [comment]
I think they are doing the update.
You can see there is new setting section on the bottom.

**Comment by jamespfennell** [comment]
Thank you so much for the bug report, it's really appreciated. It's working again now.

I currently have no idea what happened. The database that the app uses was totally wiped out at around 12 noon NYC time - while I was at work. Not sure if it was malicious actor somehow, still trying to figure it out.

**Comment by jamespfennell** [comment]
Okay not a malicious actor :)

This morning I enabled a new agent on the VM that automatically restarts the app if new changes to the app are made on GitHub. At 12:08:32 this agent triggered a restart (due to a bug in the agent, but whatever) and this seems to have blown away the database. Restarts shouldn't do that! I can change the agent config so that it also doesn't restart the database, which would avoid this happening again here.

**Comment by jamespfennell** [comment]
Hmmmmm even weirder: I just restarted the entire VM and the data that got wiped at noon today ... reappeared! Seems something is not right with the Docker volume configuration for my Postgres instance.

**Comment by jamespfennell** [comment]
I'm going to close the bug as there's nothing else to do here - the app is working and the trigger for this failure has been fixed.

I would love to understand what happened here but it just seems completely inexplicable. The Docker volume storing the Postgres data was wiped when the Postgres container was recreated, so I reinitialized the DB, but then when I restarted the VM the new data was gone and the old data came back....totally crazy.

**Comment by jamespfennell** [comment]
Okay I figured out what happened here. The new redeployment agent I wrote triggered a recreate of the Postgres Docker image the app uses. The problem is that the bind mounts for this image are specified using the $HOME env variable and the agent runs as the root user (instead of the james user). So this recreate operation mounted an empty directory into the Postgres image, causing the outage. When I manually recreated the Postgres image it reverted to using the right mount point.
